SET SERVEROUTPUT ON
CREATE OR REPLACE TRIGGER CHECKAGE
BEFORE INSERT OR UPDATE
ON SAILORS
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('Checking age: ' || :NEW.AGE);

	IF :NEW.AGE IS NOT NULL AND :NEW.AGE < 18 THEN
		DBMS_OUTPUT.PUT_LINE('ERROR: AGE TOO LOW');
		RAISE_APPLICATION_ERROR(-20000, 'Sailor must be an Adult');
	END IF;

	DBMS_OUTPUT.PUT_LINE('Age is valid');
END;
/