SET SERVEROUTPUT ON
CREATE OR REPLACE TRIGGER CHECKRATING
BEFORE DELETE
ON SAILORS
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('Checking age: ' || :NEW.AGE);

	IF :NEW.AGE IS NOT NULL AND :NEW.RATING > 5 THEN
		DBMS_OUTPUT.PUT_LINE('ERROR: TOO GOOD TO REMOVE');
		RAISE_APPLICATION_ERROR(-20000, 'Sailor must have poor performance');
	END IF;

	DBMS_OUTPUT.PUT_LINE('Age is valid');
END;
/